general:
    run_type: all

    asic_set: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

    module: null
    channel: null

    partition: all
    #partition: cfel

    temperature: null
    use_interleaved: True

drscs:
    safety_factor: 1000
    current: [itestc20, itestc80, itestc150]

dark:
    tint: tint150ns

xray:
    element: Cu

preprocess:
    # number of nodes to use
    n_jobs: 1
    # how many subprocesses should be launched per asic
    n_processes: 1

    time_limit: 00:05:00

gather:
    # number of nodes to use
    n_jobs: 2
    # how many subprocesses should be launched per asic
    n_processes: 1

    time_limit: 00:45:00

process:
    # number of nodes to use
    n_jobs: 16
    # how many subprocesses should be launched per asic
    n_processes: 10

    time_limit: 00:45:00
    #time_limit: 00:20:00

merge:
    # number of nodes to use
    n_jobs: 1
    # how many subprocesses should be launched per asic
    n_processes: 10

    time_limit: 00:05:00

join:
    # number of nodes to use
    n_jobs: 1
    # how many subprocesses should be launched per asic
    n_processes: 1

    time_limit: 00:05:00
